version: '3.7'

volumes:
  db:
    external: true

networks:
  kbm:
    external: true

services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    ports:
      - '33062:3306'
    environment:
      - 'MYSQL_DATABASE=kbm'
      - 'MYSQL_USER=homestead'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=true'
    networks:
      - kbm

  app:
    build:
      context: .
      target: php
    container_name: app
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app/
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8080:8080
    command: php -S 0.0.0.0:8080
    depends_on:
      - db
    networks:
      - kbm
